// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNu08mH5gKrWIpgV_CHH29_NoaX88iePk',
    appId: '1:659452171964:web:b3381bbc0d2278e8aae2b9',
    messagingSenderId: '659452171964',
    projectId: 'flash-chat-38d11',
    authDomain: 'flash-chat-38d11.firebaseapp.com',
    databaseURL: 'https://flash-chat-38d11-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flash-chat-38d11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGHVT3fIO_eSV3YPckJ75oHSgfDh0krwY',
    appId: '1:659452171964:android:317ebcf5370383f7aae2b9',
    messagingSenderId: '659452171964',
    projectId: 'flash-chat-38d11',
    databaseURL: 'https://flash-chat-38d11-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flash-chat-38d11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwuG6f8tVq4WJNfHkrc2JNeUzmOVpZQIw',
    appId: '1:659452171964:ios:61eaa11b4c7f8d65aae2b9',
    messagingSenderId: '659452171964',
    projectId: 'flash-chat-38d11',
    databaseURL: 'https://flash-chat-38d11-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flash-chat-38d11.appspot.com',
    iosClientId: '659452171964-t2av94udopigfdr22pd810o3vsmusq9c.apps.googleusercontent.com',
    iosBundleId: 'ios.example.app',
  );
}
